[[news]]
date = "2026-08"
content = "PASS: Rethinking Pathology Image Analysis through Shuffling 发表于 npj Biomedical Innovations。"

[[news]]
date = "2026-05"
content = "Cellflow: Advancing pathological image augmentation from spatial views to temporal trajectories 发表于 Medical Image Analysis。"

[[news]]
date = "2025-12"
content = "StainExpert: A Unified Multi-Expert Diffusion Framework for Multi-Target Pathological Stain Translation 发表于 IEEE Transactions on Medical Imaging。"
